algolia/algolia-react-boilerplate

package.json, src/components/carousels/HomeCarousel.jsx
=> fix: empty query for carousels

src/config/animationConfig.js, src/pages/ProductDetails.jsx
What:
👉 Fix lag on PDP 
Why:
👉 Better UX/UI
=> fix: fix pdp lag

src/config/refinementsConfig.js
What:  remove unnecessary header attribute from refinements config
Why: refactoring
How: delete header attribute
Locally, clicking around a lot 🤷
=> chore: remove unnecessary header attribute from refinements config

.gitignore
=> 🙂:  remove an extra line between the sections and add a comment to be consistent

src/components/carousels/HomeCarousel.jsx
=> fix: div to motion.div

src/components/banners/HomeBanners.jsx, src/scss/banners/homeBanner2.scss, src/scss/banners/homeBanner3.scss
What: Encase the whole banner button in a link
Why: So clicking anywhere on the button will trigger link
How: Move Link component up the component tree a little
Usage: As normal, click anywhere on the button from now on
Ran locally
Not needed
=> fix: link for banner button

README.md
What: Update docs to add install commands
Why: Because we need to tell SEs how to run the project
How: By updating the readme
Usage: N/a
Saw in the preview
=> Updated Readme: Showing Start Commands

src/components/facets/Facets.jsx, src/components/facets/SCSS/partials/_colorsRefinement.scss
What: Add a cursor pointer on color Facet + remove old component commented
Why: Better UX
=> fix: cursor pointer color facet + remove comments in facet

src/config/languagesConfig.js, src/config/personaConfig.js, src/config/segmentConfig.js
What: Remove input in select
✅
=> fix: Remove input from react select

src/scss/index.scss
What: Importing Skeleton Styles
Why: So we can see the skeleton loading
Usage: https://share.vidyard.com/watch/jnFuhYmhP8UztiQcK3neWS
Localhost (please see video)
=> stylesheet import for skeleton

src/components/recommend/trending/TrendingFacetValues.jsx, src/components/recommend/trending/TrendingFacetsItem.jsx, src/components/skeletons/CustomSkeleton.jsx, src/scss/index.scss
What: https://github.com/algolia/algolia-react-boilerplate/issues/258
Why: Because a component was re-rendering inside another component creating a dependancy
How: Separating components
Usage: https://share.vidyard.com/watch/wBufmzRhAjih6U8c6GCvSK
Localhost
=> BUG: Slider Bug on Trending Brands

src/pages/searchResultPage/SearchResultsPage.jsx
What: Refactor code 
**CHECK VIDEO BELLOW TO SEE SRP WORKING NORMALLY**
Usage: https://share.vidyard.com/watch/sMruRmbigQFh1SRzP7wxCu?
Localhost
=> Refactor: Cleaned Unused Old Skeleton Logic

src/components/header/components/HeaderLaptop.jsx, src/components/searchbox/SCSS/searchbox.scss, src/components/searchbox/SearchBox.jsx, src/components/voicesearch/SCSS/voicesearch.scss, src/components/voicesearch/VoiceSearch.jsx, src/config/searchboxConfig.js
What:
👉 Custom VoiceSearch with hooks
Why:
👉 Update
✅
=> feature: VoiceSearch with Hooks

README.md, src/Main.jsx, src/components/modals/CustomModal.jsx, src/config/demoGuideConfig.js, src/scss/partials/_index.scss, src/scss/partials/_modals.scss, src/utils/ErrorHandler.jsx
What: finished displaying network errors and built config to it, built custom modal
Why: provide guidance to SE's
How: showing api errors 
Usage: 
`export const showNetworkErorrs = atom({
key: 'showNetworkErorrs',
default: true,
});`
Localhost
Create a bad request on the frontend and you will see the output. (change the api key to invalid)
=> Handling API Errors

src/components/hits/CustomHits.jsx, src/components/hits/components/CustomHits.jsx, src/components/selector/Selectors.jsx, src/utils/ErrorHandler.jsx
What: Issue 279
Why: displaying an error message in console unable to parse json
How: wrapped in try catch 
Localhost
=> Fix: Error Handling Bug

src/components/banners/HomeBanners.jsx, src/components/banners/SCSS/homeBanner.scss
=> optimised FCP

src/Main.jsx, src/components/carousels/HomeCarousel.jsx, src/components/hits/SCSS/skeleton.scss, src/components/skeletons/CustomSkeleton.jsx, src/pages/homepage/HomePage.jsx
=> Work on CLS

src/Main.jsx, src/components/carousels/HomeCarousel.jsx, src/components/header/SCSS/header.scss, src/components/header/components/HeaderLaptop.jsx, src/components/hits/SCSS/skeleton.scss, src/components/searchbox/SCSS/searchbox.scss, src/components/skeletons/CustomSkeleton.jsx, src/config/carouselConfig.js, src/pages/homepage/HomePage.jsx
=> Remove all CLS

src/components/banners/HomeBanners.jsx, src/pages/homepage/HomePage.jsx, src/pages/homepage/homepage.scss, src/scss/partials/_fonts.scss, src/scss/partials/_mixin.scss
=> Remove LCP

src/components/banners/HomeBanners.jsx
=> create useEffect for loading img banner only on mount

LICENCE.md
What: Add an MIT licence
Why: Best practice
How: Licence template
Usage: As normal
N/A
=> chore: create MIT LICENSE

package.json
What: remove, upgrade and pin correct vite packages
Why: remove any confusion in line with using vite 3
How: N/A
Usage: yarn as normal
N/A
Ran locally
N/A
=> chore: correct vite packages

src/components/hits/Hits.jsx, src/components/hits/components/CustomHits.jsx, src/components/hits/components/InfluencerCard.jsx, src/components/hits/components/NoCtaCard.jsx, src/components/hits/components/SalesCard.jsx, src/components/hits/components/injected-hits/InjectedHits.jsx, src/components/searchresultpage/srpLaptop/SrpLaptop.jsx, src/scss/partials/_mixin.scss
What:
👉 Infinite scroll on SRP (with and without content injection)
Why:
How: 
Usage:
https://share.getcloudapp.com/d5uOjmL8
=> infinite scroll done

src/Main.jsx, src/components/carousels/HomeCarousel.jsx, src/components/carousels/SCSS/carousels.scss, src/pages/homepage/HomePage.jsx, src/pages/searchResultPage/SearchResultsPage.jsx
What: made carousel draggable and refactored unused logic 
Why: Issue https://github.com/algolia/algolia-react-boilerplate/issues/272
How: Framer motion
Usage: Grab and slide
Localhost
=> Carousel Draggable

README.md
=> chore: readme file change and remove React Select part

src/components/appliedRules/PersonaScore.jsx
=> fix: when I switched of persona the event switcher didn't persist

src/config/carouselConfig.js, src/config/translation.js
What: Wrong Title and old code into config carousels.
=> fix: change title config for carousels

src/config/algoliaEnvConfig.js
What: Move around the code in algoliaEnvConfig, add comments
Why: Make algoliaEnvConfig clearer for new users
How: Simple re-order and document for now
Usage: As normal
NA
=> chore: re-order config and document with comments

src/components/facets/Facets.jsx, src/components/facets/SCSS/facets.scss
What: Info message if no facets
Why: Help SE if no facets returned
How: useInstantSearch hook
Usage: as normal
Local with and without facet order defined
NA
=> fix: info message if no facets

src/pages/productDetailsPage/ProductDetails.jsx
What: Fix issue recommend on PDP
✅
=> fix: issue 335

src/components/header/components/Navigation.jsx
What: checks defined filter instead
Why: lets user change link in headerConfig.js from "All"
How: check filter is empty or not
Usage: n/a
Changed first link's name in headerConfig.js to 'All Products' and clicked
=> check filter instead of name

src/components/facets/SCSS/facets.scss
=> added back show more css in facets SRP

src/components/searchresultpage/srpLaptop/SrpLaptop.jsx, src/config/navigationConfig.js
What: Hotfix on filter due to wrong name of variable
✅
=> fix: hotfix rawFilter

src/components/facets/components/PriceSlider.jsx
=> refactor priceInput

src/Main.jsx, src/components/appliedRules/PersonaScore.jsx, src/components/appliedRules/SCSS/appliedRules.scss
What: Responsiveness issue with personascore
Why: display nicely on mobile
How: scss
Localhost
=> styled persona score for mobile

src/components/banners/HomeBanners.jsx, src/components/banners/SCSS/homeBanner.scss, src/scss/partials/_mixin.scss
What: fluid font (banner home) & banner fix on mobile
Why: fix 
How: using clamp function (css)
https://share.getcloudapp.com/WnuDAyxb
=> fluid font & banner fix on mobile

README.md
What: Detail what you need to have installed in order to get the repo up and running
Why: If you don't know what version of node you need etc you won't be able to run the repo
How: Small readme section
Usage: as normal
N/A
N/A
=> chore: add a small pre-req section and also link to demo guides

src/components/appliedRules/AppliedRules.jsx, src/components/appliedRules/SCSS/appliedRules.scss, src/hooks/useDebounce.jsx
What:
👉 Better UI panel for applied rules
👉 Handling no rule apply case
=> Feature/1.0 current rules panel UI

src/App.jsx, src/config/scrollOnTop.js
What: https://app.clickup.com/t/2rreu34
Why:
How: 
Create a function with router in config file
Usage:
✅
=> feat: scroll on top

src/components/demoGuide/components/SearchPersona.jsx, src/config/algoliaEnvConfig.js
What: Closes #378 
Why: Clearer naming
How:  Variable naming
Usage: As normal
=> chore: new api key name for persona strategy call

src/components/header/components/DemoGuideOpener.jsx
=> close the facet panel when the demo tour is open

src/pages/productDetailsPage/ProductDetails.jsx, src/scss/partials/_variables.scss
What: Fix recommend breaking on mobile bug
Why: -
How: Syntax for navigate hook
Usage: As normal
Localhost
N/A
=> fix: navigate correctly back from PDP to SRP

src/components/carousels/SCSS/carousels.scss, src/components/searchresultpage/srpLaptop/Noresult.jsx
What:
👉 Condition was needed to avoir errors when Related product feature was turned off
✅
=> condition created for No result Related product

src/components/facets/components/PriceSlider.jsx
=> chore: english text for price slider button

src/Main.jsx, src/components/carousels/HomeCarousel.jsx, src/components/federatedSearch/components/Category.jsx, src/components/federatedSearch/components/Products.jsx, src/components/header/components/Navigation.jsx, src/components/hits/Hits.jsx, src/components/recommend/relatedItems/RelatedProducts.jsx, src/components/searchbox/SCSS/searchbox.scss, src/components/searchbox/components/SearchInCategory.jsx, src/pages/productDetailsPage/ProductDetails.jsx
What:
👉 Created a slug URL for category pages
👉 Hot fix for searching in categories (searchbox)
✅
=> create slug URL for category pages

src/components/header/components/Navigation.jsx, src/components/searchbox/SearchBox.jsx, src/components/searchbox/components/SearchInCategory.jsx, src/components/searchresultpage/srpLaptop/SrpLaptop.jsx, src/config/navigationConfig.js
What: Pass the query and category through URL as well as state
Why: Allows us to track queries using google analytics etc.
How: react router and state configuration
Usage: as normal
Localhost
N/A
=> feat: track query and category through URL

src/components/header/components/HeaderMobile.jsx
=> hot fix fixing voicesearch on Mobile

src/App.jsx, src/Index.jsx, src/Main.jsx, src/components/banners/HomeBanners.jsx, src/pages/homepage/HomePage.jsx
=> serve smaller img for mobile on home

index.html, src/components/banners/HomeBanners.jsx, src/components/header/components/HeaderMobile.jsx
=> fixing typo

index.html, src/scss/partials/_mixin.scss
=> removed font awesome call

index.html, src/components/banners/HomeBanners.jsx
=> trying to preload banne

src/components/searchbox/SearchBox.jsx
What:
👉 Debounce on search was causing unwanted page refresh 
Why:
How: 
Usage:
✅
=> remove debounce on search

index.html
=> use preconnect for goofle font

index.html
=> test preload font V2

src/components/carousels/SCSS/carousels.scss
What:
👉 Product card are now consistent troughout the app
=> product card in Carousel consistent with product card in hits

public/static/images/arrowDown.svg, public/static/images/arrowUp.svg, src/components/hits/Hits.jsx, src/components/hits/SCSS/ranking.scss, src/components/hits/components/RankingIcon.jsx, src/config/personaConfig.js
What:
Usage: turn on in the persona config by default when personas selected
Localhost
=> added ranking Icons to persona

src/components/hits/Hits.jsx, src/components/hits/SCSS/hits.scss, src/scss/partials/_mixin.scss
What:
👉 When image have a variant or an alt the card behavior is now normal 
✅
=> fix imageAlt bug

src/components/carousels/HomeCarousel.jsx, src/components/carousels/SCSS/carousels.scss, src/components/hits/SCSS/skeleton.scss, src/components/hits/components/HitsSkeletonLoader.jsx, src/pages/homepage/HomePage.jsx
What: Skeleton loaders
How: 
Localhost
=> done skeleton loaders for carousels on homepage

src/components/carousels/HomeCarousel.jsx, src/components/carousels/SCSS/carousels.scss, src/components/hits/components/HitsSkeletonLoader.jsx
=> changed for mobile

src/components/hits/components/CustomHits.jsx
What: Fix showMore no function issue
=> fix: remove showMore from useEffect

README.md, src/components/facets/Facets.jsx
What:
https://app.clickup.com/t/33e4zqv
=> Cu 33e4zqv sometimes on reload on srp you have an issue comes from facet ordering 

src/components/cart/CartModal.jsx, src/pages/productDetailsPage/ProductDetails.jsx
What: Fix and remove unused Const
=> fix: remove cartstate unused and removeItem too

src/components/cart/CartModal.jsx, src/components/cart/RelatedProductsCart.jsx, src/components/cart/SCSS/cartModal.scss, src/pages/productDetailsPage/ProductDetails.jsx
What: Add related product to the cart
Why: Key feature
How: If articles are present into the cart take all the objectIds and generate an array
Usage:
=> Cu 32q94cm add related product in the cart 

src/components/searchbox/SCSS/searchbox.scss, src/scss/partials/_mixin.scss
What:
👉 Better searchbox that has focus when click in it
👉 Good practises
✅
=> better searchBox

src/components/appliedRules/SCSS/appliedRules.scss, src/components/banners/SCSS/homeBanner.scss, src/components/carousels/SCSS/carousels.scss, src/components/cart/SCSS/cartModal.scss, src/components/demoGuide/SCSS/alertNavigation.scss, src/components/demoGuide/SCSS/demoGuide.scss, src/components/facets/SCSS/facets.scss, src/components/facets/SCSS/partials/_clearRefinement.scss, src/components/facets/SCSS/partials/_currentRefinement.scss, src/components/facets/SCSS/partials/_hierarchicalRefinement.scss, src/components/facets/SCSS/partials/_priceRefinement.scss, src/components/federatedSearch/SCSS/federatedSearch.scss, src/components/header/SCSS/header.scss, src/components/hits/SCSS/hits.scss, src/components/hits/SCSS/partials/_badge.scss, src/components/loader/SCSS/loader.scss, src/components/recommend/SCSS/recommend.scss, src/components/redirects/SCSS/redirect.scss, src/components/searchbox/SCSS/searchbox.scss, src/components/searchresultpage/SCSS/searchResultsPage.scss, src/components/searchresultpage/SearchResults/SearchResults.jsx, src/components/selector/selectors.scss, src/components/voicesearch/SCSS/voicesearch.scss, src/config/demoGuideConfig.js, src/pages/productDetailsPage/SCSS/productDetails.scss, src/scss/partials/_mixin.scss, src/scss/partials/_variables.scss
What:
👉 Changing naming of one CSS variable $second-color ➡ $secondary-color (@BenDanielGreep  Suggestions for more correct english 🙏) 
👉 Get the query through URL params (handled by react router) when not empty
Why:
👉 Protect us against errors
✅
=> change naming of css variables and get query through URL params

src/components/hits/components/CustomHits.jsx, src/components/hits/components/injected-hits/InjectedHits.jsx, src/components/hits/components/injected-hits/injectContent.js, src/components/searchbox/SearchBox.jsx, src/components/searchresultpage/SearchResults/SearchResults.jsx, src/config/featuresConfig.js, src/pages/homepage/HomePage.jsx, src/pages/searchResultPage/SearchResultsPage.jsx
=> [DRAFT TO TEST BUG IN PRODUCTION]testing

src/config/demoGuideConfig.js
What: Small cleanup of demo guide config
Why: ease of use
How: correct grammer, remove semi colons, re-structure
Usage: as normal
Localhost
=> fix: clean up demo guide

src/config/algoliaEnvConfig.js
=> fix: amend articles index name

src/components/carousels/SCSS/carousels.scss, src/config/featuresConfig.js
What:
👉 Injected hit pass to true
👉Style in Federated
✅
=> injected hit true

src/components/cart/ArticlesCard.jsx, src/components/cart/CartModal.jsx, src/components/fbtPdp/FbtAddAll.jsx, src/config/cartFunctions.js, src/config/predictConfig.js, src/pages/productDetailsPage/ProductDetails.jsx
=> fix: develop merge-issues

src/components/recommend/fbtItems/FbtProducts.jsx, src/components/recommend/relatedItems/RelatedProducts.jsx
What: Issue on multiple sending of events, I removed actually the sendEvent hooks from Fbt and Related
✅
=> remove events on Fbt and Related due to multiple rerender

README.md, src/components/predict/PredictUserProfileProvider.jsx, src/components/selector/Selectors.jsx, src/config/languagesConfig.js, src/config/translation.js
What:
👉 Leverage the fact that we had to work with an italian index on Off-White demo to add it for the BP. It might makes us win some time for next demos
✅
=> Italian language added

src/assets/svg/SvgIndex.jsx, src/components/cart/ArticlesCard.jsx, src/components/cart/CartModal.jsx, src/components/cart/SCSS/cartModal.scss, src/components/federatedSearch/SCSS/federatedSearch.scss, src/scss/partials/_mixin.scss
What:
👉 Reuse Federated Search style as Mixin for product in cart
👉 Change cart logic when removing one item of the cart whereas others are still in
Why:
👉 Less code
👉 More Homegeneous style
=> use mixin to set the cart product as federated => DRY

src/components/header/components/HeaderLaptop.jsx, src/components/recommend/relatedItems/RelatedProducts.jsx
What: [ClickUp](https://app.clickup.com/t/31b7gnp)
✅
=> fix: open cart modal on click item

src/components/header/SCSS/header.scss, src/scss/partials/_globals.scss
What:
👉 When reaches 1600px the body is centered 
✅
=> center the body

src/components/header/SCSS/header.scss, src/components/header/components/HeaderLaptop.jsx, src/components/recommend/SCSS/recommend.scss, src/scss/partials/_mixin.scss
What: [ClickUp](https://app.clickup.com/t/31b7fck)
+
Fix on icon opening zone which was too large
✅
=> fix: icon cursor and opening on SVg + overflow of trending carts

src/Main.jsx, src/components/header/Header.jsx, src/components/header/SCSS/header.scss, src/components/header/components/HeaderLaptop.jsx, src/scss/partials/_globals.scss
What:
👉 Make the header full-width when > 1600px
✅
=> make the header full width

src/components/federatedSearch/SCSS/federatedSearch.scss, src/components/federatedSearch/components/Products.jsx
What:
👉 Added highlight to federated Search
=> add highlight product name in Federated

src/components/facets/SCSS/facets.scss, src/components/recommend/trending/TrendingFacetValues.jsx
What:
Margin on title when facets are deployed
https://share.getcloudapp.com/kpuW0vAG
=> fix: trending title moved

src/components/facets/SCSS/facets.scss, src/components/recommend/trending/TrendingFacetValues.jsx
What:
https://app.clickup.com/t/322471q
=> fix: trending items and facets deployed button

.npmrc, apps/boilerplate-front-end/src/components/hits/components/Price.jsx, pull_request_template.md
What:
👉 Display "price unavailable" when no price are in records
Why:
👉 Avoid bugs
How:
` const hitPrice = get(hit, price) ? get(hit, price) : 'unavailable price'`
=> fixing price issue when no price in records

apps/boilerplate-front-end/src/components/voicesearch/VoiceSearch.jsx, apps/boilerplate-front-end/src/scss/partials/_mixin.scss
What:
👉 Fix crash when going on mobile
✅
=> fixes searchbox crash

apps/boilerplate-front-end/src/components/header/SCSS/header.scss, apps/boilerplate-front-end/src/components/header/components/OktaAuth.jsx
=> feat: add okta logout function

apps/boilerplate-front-end/src/components/federatedSearch/FederatedSearch.jsx
What:
👉 Quick change of UI for a better UX in the federated
Why:
👉 White spaces are removed 
✅
=> UX change, adding Query cat on the left side of federated

README.md, apps/boilerplate-documentation/docs/02-Getting Started/getting-started.md
What:
👉 Documentation update : 
1/ Clarification about the root directory
2/ Precision if encounter an error during installation (fix: install a package separetely)
👌
=> update docs in case of error or misunderstanding

apps/boilerplate-front-end/src/components/federatedSearch/FederatedSearch.jsx, apps/boilerplate-front-end/src/components/federatedSearch/components/Products.jsx, apps/boilerplate-front-end/src/components/header/SCSS/header.scss
What:
👉 Small issue when passing props from federated to child component "product"
👉 Fix some styles in the mobile header 
Why:
How:
Usage:
Tested
=> refacto product part in federated + Fix style in header mobile

apps/boilerplate-front-end/README.md
What:
👉 Update readMe & troubleshooting section
=> update readMe / troubleshooting section
